export function assetLinks(env) {
  const raw = String(env.ANDROID_CERT_SHA256 || '').trim().toUpperCase();
  const fingerprint = /^[0-9A-F]{64}$/.test(raw) ? raw.match(/../g).join(':') : raw;
  if (!/^(?:[0-9A-F]{2}:){31}[0-9A-F]{2}$/.test(fingerprint)) return new Response(null, { status: 404 });
  return Response.json([{
    relation: ['delegate_permission/common.handle_all_urls'],
    target: {
      namespace: 'android_app',
      package_name: 'br.com.rcconstrutec.centrocustos',
      sha256_cert_fingerprints: [fingerprint],
    },
  }], { headers: { 'cache-control': 'public, max-age=3600' } });
}

export function resetPage() {
  return new Response(`<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer"><title>Redefinir senha · Construtec</title>
<style>
*{box-sizing:border-box}html,body{min-height:100%;margin:0}body{font:15px system-ui,sans-serif;color:#fff;background:#021820;overflow-x:hidden}
.blob{position:fixed;border-radius:50%;pointer-events:none;filter:blur(64px);animation:drift 14s alternate infinite}.a{width:300px;height:300px;left:-80px;top:-60px;background:#12a9d1;opacity:.55}.b{width:320px;height:320px;right:-110px;top:180px;background:#0b5a70;opacity:.8;animation-duration:17s}.c{width:300px;height:300px;left:-40px;bottom:-120px;background:#1a4da1;opacity:.45;animation-duration:19s}
.dots{position:fixed;inset:0;pointer-events:none;background-image:radial-gradient(rgba(255,255,255,.07) 1px,transparent 1px);background-size:18px 18px}.glow{position:fixed;inset:0;pointer-events:none;background:radial-gradient(180px circle at var(--x,50%) var(--y,50%),rgba(95,208,238,.22),transparent 70%)}
main{position:relative;max-width:440px;margin:auto;padding:60px 18px 30px}.brand{font-weight:800;letter-spacing:.1em;font-size:23px;margin:15px 0 34px}.brand span{color:#5fd0ee}.back{display:inline-flex;align-items:center;min-height:44px;color:#5fd0ee;text-decoration:none;margin-bottom:8px}
.card{padding:18px;border-radius:22px;background:rgba(255,255,255,.07);backdrop-filter:blur(18px) saturate(140%);box-shadow:inset 0 0 0 1px rgba(255,255,255,.16),0 20px 50px rgba(0,0,0,.35)}h1{font-size:25px;margin:4px 0 12px}p{color:#b9d4dd;line-height:1.5}label{display:block;color:#b9d4dd;font-size:12px;font-weight:600;margin:18px 0 7px}input{width:100%;height:48px;border:0;border-radius:12px;color:#fff;background:rgba(255,255,255,.08);box-shadow:inset 0 0 0 1px rgba(255,255,255,.18);padding:0 14px;font:inherit}input:focus{outline:0;box-shadow:inset 0 0 0 2px #12a9d1;background:rgba(18,169,209,.08)}button{width:100%;height:52px;border:0;border-radius:12px;color:#fff;font:600 15px system-ui;background:linear-gradient(100deg,#12a9d1,#0d7f9f);box-shadow:0 10px 24px rgba(18,169,209,.28);cursor:pointer;margin-top:20px}button:disabled{opacity:.55;cursor:default}.bars{display:flex;gap:6px;margin-top:14px}.bars i{height:6px;flex:1;border-radius:9px;background:rgba(255,255,255,.18)}.bars[data-strength="1"] i:first-child,.bars[data-strength="2"] i:nth-child(-n+2){background:#f2b544}.bars[data-strength="3"] i:nth-child(-n+3){background:#5fd0ee}.bars[data-strength="4"] i{background:#3ddc84}.checklist{display:grid;grid-template-columns:1fr 1fr;gap:8px;color:#b9d4dd;font-size:12px;margin:14px 0}.checklist b{font-weight:500}.checklist b.pass{color:#3ddc84}.message{min-height:20px;color:#f2b544;font-size:12.5px;font-weight:600;margin:12px 0 0}#success{display:none}#success svg{width:88px;height:88px;color:#3ccf8e}#success a{color:#5fd0ee;display:inline-flex;align-items:center;min-height:44px}@keyframes drift{to{transform:translate(35px,25px)}}@media(prefers-reduced-motion:reduce){.blob{animation:none}}
</style></head><body><div class="blob a"></div><div class="blob b"></div><div class="blob c"></div><div class="dots"></div><div class="glow"></div><main><div class="brand">CONSTRU<span>TEC</span></div><a class="back" href="/">Voltar ao login</a><section class="card" id="form-card"><h1>Crie uma senha nova</h1><p>Escolha uma senha segura para sua conta.</p><form id="reset-form"><label for="password">Senha nova</label><input id="password" type="password" autocomplete="new-password" required><label for="repeat">Confirme a senha</label><input id="repeat" type="password" autocomplete="new-password" required><div class="bars" id="bars" data-strength="0"><i></i><i></i><i></i><i></i></div><p id="strength" aria-live="polite">Digite uma senha</p><div class="checklist" id="checks"><b>8+ caracteres</b><b>Letra maiúscula</b><b>Um número</b><b>Um símbolo</b></div><p class="message" id="message" role="alert"></p><button id="submit" type="submit">Salvar senha</button></form></section><section class="card" id="success"><svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="43" stroke="currentColor" stroke-width="5"/><path d="M28 51l15 15 30-32" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg><h1>Senha alterada</h1><p>Por segurança, encerramos as sessões nos outros aparelhos. Entre com a senha nova para continuar.</p><a href="/">Entrar com a senha nova</a></section></main>
<script>
const token=new URLSearchParams(location.hash.slice(1)).get('t');history.replaceState(null,'',location.pathname);
const form=document.getElementById('reset-form'),password=document.getElementById('password'),repeat=document.getElementById('repeat'),message=document.getElementById('message');
const checks=[p=>p.length>=8,p=>/[A-Z]/.test(p),p=>/\\d/.test(p),p=>/[^\\p{L}\\p{N}\\s]/u.test(p)];
function update(){const met=checks.map(check=>check(password.value)),score=met.filter(Boolean).length;document.getElementById('bars').dataset.strength=String(score);document.getElementById('strength').textContent=['Digite uma senha','Fraca','Razoável','Boa','Forte'][password.value?score:0];document.querySelectorAll('#checks b').forEach((item,i)=>item.classList.toggle('pass',met[i]));return met[0]&&score>=3}
password.addEventListener('input',update);document.addEventListener('pointermove',event=>{document.documentElement.style.setProperty('--x',event.clientX+'px');document.documentElement.style.setProperty('--y',event.clientY+'px')});
if(!token)message.textContent='Link inválido. Peça outro link de redefinição.';
form.addEventListener('submit',async event=>{event.preventDefault();message.textContent='';if(!token){message.textContent='Link inválido. Peça outro link de redefinição.';return}if(!update()){message.textContent='A senha ainda está fraca. Siga a lista acima.';return}if(password.value!==repeat.value){message.textContent='As duas senhas não são iguais.';return}const button=document.getElementById('submit');button.disabled=true;try{const response=await fetch('/v1/auth/password-reset/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,password:password.value})});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível alterar a senha.');document.getElementById('form-card').style.display='none';document.getElementById('success').style.display='block'}catch(error){message.textContent=error.message}finally{button.disabled=false}});
</script></body></html>`, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store', 'referrer-policy': 'no-referrer', 'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; form-action 'self'" } });
}
