plugins { id 'com.android.application' }

android {
    namespace 'br.com.rcconstrutec.centrocustos'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.rcconstrutec.centrocustos'
        minSdk 26
        targetSdk 35
        versionCode 31014
        versionName '3.1.0-rc.14'
    }
}
